package com.wu.billersplus.connector.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2018-04-06T16:01:51.791-03:00
 * Generated source version: 2.6.6
 *
 */
@WebServiceClient(name = "genericoMethodsService",
                  wsdlLocation = "wsstandard-v5.wsdl",
                  targetNamespace = "http://operations.genericows.sibs.com.ar")
public class GenericoMethodsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://operations.genericows.sibs.com.ar", "genericoMethodsService");
    public final static QName GenericoMethods = new QName("http://operations.genericows.sibs.com.ar", "genericoMethods");
    static {
        URL url = GenericoMethodsService.class.getResource("wsstandard-v5.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GenericoMethodsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsstandard-v5.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GenericoMethodsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GenericoMethodsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericoMethodsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GenericoMethodsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GenericoMethodsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GenericoMethodsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MethodsWS
     */
    @WebEndpoint(name = "genericoMethods")
    public MethodsWS getGenericoMethods() {
        return super.getPort(GenericoMethods, MethodsWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MethodsWS
     */
    @WebEndpoint(name = "genericoMethods")
    public MethodsWS getGenericoMethods(WebServiceFeature... features) {
        return super.getPort(GenericoMethods, MethodsWS.class, features);
    }

}
