package com.wu.billersplus.connector.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2018-04-06T16:01:51.739-03:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://operations.genericows.sibs.com.ar", name = "MethodsWS")
@XmlSeeAlso({ObjectFactory.class})
public interface MethodsWS {

    @WebResult(name = "consultaReturn", targetNamespace = "http://operations.genericows.sibs.com.ar")
    @RequestWrapper(localName = "consulta", targetNamespace = "http://operations.genericows.sibs.com.ar", className = "com.wu.billersplus.connector.ws.Consulta")
    @WebMethod
    @ResponseWrapper(localName = "consultaResponse", targetNamespace = "http://operations.genericows.sibs.com.ar", className = "com.wu.billersplus.connector.ws.ConsultaResponse")
    public com.wu.billersplus.connector.ws.ConsultaResp consulta(
        @WebParam(name = "hdReq", targetNamespace = "http://operations.genericows.sibs.com.ar")
        com.wu.billersplus.connector.ws.HeaderReq hdReq,
        @WebParam(name = "utility", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String utility,
        @WebParam(name = "cod_barra", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String codBarra,
        @WebParam(name = "codigo_cliente", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String codigoCliente
    );

    @WebResult(name = "reversaReturn", targetNamespace = "http://operations.genericows.sibs.com.ar")
    @RequestWrapper(localName = "reversa", targetNamespace = "http://operations.genericows.sibs.com.ar", className = "com.wu.billersplus.connector.ws.Reversa")
    @WebMethod
    @ResponseWrapper(localName = "reversaResponse", targetNamespace = "http://operations.genericows.sibs.com.ar", className = "com.wu.billersplus.connector.ws.ReversaResponse")
    public com.wu.billersplus.connector.ws.ReversaResp reversa(
        @WebParam(name = "hdReq", targetNamespace = "http://operations.genericows.sibs.com.ar")
        com.wu.billersplus.connector.ws.HeaderReq hdReq,
        @WebParam(name = "terminalOriginal", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String terminalOriginal,
        @WebParam(name = "cajeroOriginal", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String cajeroOriginal,
        @WebParam(name = "fechaHoraOriginal", targetNamespace = "http://operations.genericows.sibs.com.ar")
        javax.xml.datatype.XMLGregorianCalendar fechaHoraOriginal,
        @WebParam(name = "nroSecuenciaOriginal", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String nroSecuenciaOriginal,
        @WebParam(name = "tipoReversa", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String tipoReversa,
        @WebParam(name = "utility", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String utility,
        @WebParam(name = "amount", targetNamespace = "http://operations.genericows.sibs.com.ar")
        int amount
    );

    @WebResult(name = "directaReturn", targetNamespace = "http://operations.genericows.sibs.com.ar")
    @RequestWrapper(localName = "directa", targetNamespace = "http://operations.genericows.sibs.com.ar", className = "com.wu.billersplus.connector.ws.Directa")
    @WebMethod
    @ResponseWrapper(localName = "directaResponse", targetNamespace = "http://operations.genericows.sibs.com.ar", className = "com.wu.billersplus.connector.ws.DirectaResponse")
    public com.wu.billersplus.connector.ws.DirectaResp directa(
        @WebParam(name = "hdReq", targetNamespace = "http://operations.genericows.sibs.com.ar")
        com.wu.billersplus.connector.ws.HeaderReq hdReq,
        @WebParam(name = "check", targetNamespace = "http://operations.genericows.sibs.com.ar")
        com.wu.billersplus.connector.ws.Check check,
        @WebParam(name = "utility", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String utility,
        @WebParam(name = "barCode", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String barCode,
        @WebParam(name = "medioPago", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String medioPago,
        @WebParam(name = "creditCard", targetNamespace = "http://operations.genericows.sibs.com.ar")
        java.lang.String creditCard,
        @WebParam(name = "amount", targetNamespace = "http://operations.genericows.sibs.com.ar")
        int amount
    );
}
